/**
* frmConsultas.java
* Apr 7, 2023 9:04:19 PM
* 
*/ 

package Presentacion;

import Dominio.Licencia;
import Dominio.Placa;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Objects;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Descripción de la clase: 
 * Clase encargada de mostrar todo el historial de consultas
 * @author Joel Antonio Lopez Cota ID:228926 y David de Jesus Sotelo Palafox ID:229384
 */
public class frmConsultas extends javax.swing.JFrame {

    /** Creates new form frmConsultas
     * @param licencias 
     */
    public frmConsultas(List<Licencia> licencias,List<Placa> placas) {
        initComponents();{
        cargarTablaLicencias(licencias);
        cargarTablaPlacas(placas);
    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        txtSolicitarPlacas = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();
        pnlTablaLicencia = new javax.swing.JPanel();
        scPanelLicencias = new javax.swing.JScrollPane();
        tblLicencias = new javax.swing.JTable();
        pnlTablaPlacas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlacas = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        txtPlacas = new javax.swing.JLabel();
        txtLicencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlTitulo.setBackground(new java.awt.Color(117, 37, 37));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(221, 66));

        txtSolicitarPlacas.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtSolicitarPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas.setText("Consultas");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlInfo.setBackground(new java.awt.Color(255, 204, 153));

        pnlTablaLicencia.setBackground(new java.awt.Color(255, 204, 153));

        tblLicencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Fecha Expedicion", "Fecha Vigencia", "Costo", "Activa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scPanelLicencias.setViewportView(tblLicencias);

        javax.swing.GroupLayout pnlTablaLicenciaLayout = new javax.swing.GroupLayout(pnlTablaLicencia);
        pnlTablaLicencia.setLayout(pnlTablaLicenciaLayout);
        pnlTablaLicenciaLayout.setHorizontalGroup(
            pnlTablaLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLicenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scPanelLicencias, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTablaLicenciaLayout.setVerticalGroup(
            pnlTablaLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLicenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scPanelLicencias, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTablaPlacas.setBackground(new java.awt.Color(255, 204, 153));
        pnlTablaPlacas.setPreferredSize(new java.awt.Dimension(626, 125));

        tblPlacas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Placa", "Fecha Expedicion", "Fecha Vigencia", "Serie del Carro", "Costo", "Activa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPlacas);

        javax.swing.GroupLayout pnlTablaPlacasLayout = new javax.swing.GroupLayout(pnlTablaPlacas);
        pnlTablaPlacas.setLayout(pnlTablaPlacasLayout);
        pnlTablaPlacasLayout.setHorizontalGroup(
            pnlTablaPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaPlacasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlTablaPlacasLayout.setVerticalGroup(
            pnlTablaPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaPlacasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        txtPlacas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacas.setText("Placas");

        txtLicencias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLicencias.setForeground(new java.awt.Color(0, 0, 0));
        txtLicencias.setText("Licencias");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlTablaPlacas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                                .addComponent(pnlTablaLicencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtLicencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablaLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPlacas)
                .addGap(18, 18, 18)
                .addComponent(pnlTablaPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
     new frmSeleccionPersonas().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
        new frmSeleccionPersonas().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTablaLicencia;
    private javax.swing.JPanel pnlTablaPlacas;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scPanelLicencias;
    private javax.swing.JTable tblLicencias;
    private javax.swing.JTable tblPlacas;
    private javax.swing.JLabel txtLicencias;
    private javax.swing.JLabel txtPlacas;
    private javax.swing.JLabel txtSolicitarPlacas;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para cargar la tabla de licencias
     * @param lista Lista de licencia
     */
    private void cargarTablaLicencias(List<Licencia> lista) {
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
         String activa="";
         DefaultTableModel modeloTabla = (DefaultTableModel) this.tblLicencias.getModel();
         modeloTabla.setRowCount(0);
         for (Licencia licencia : lista) {
             if (licencia.isActiva()) {
                 activa="Si";
             }else{
                 activa="No";
             }
             Object[] fila = {
                 licencia.getTipo(),
                 sdf.format(licencia.getFechaExpedicion().getTime()),
                 sdf.format(licencia.getFechaVigencia().getTime()),
                 "$"+licencia.getCosto(),
                 activa
             };
             modeloTabla.addRow(fila);
         }
    }

    /**
     * 
     * Metodo para cargar la tabla de las placas
     * @param placas Lista de placas
     */
    private void cargarTablaPlacas(List<Placa> placas) {
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
         String activa="";
         DefaultTableModel modeloTabla = (DefaultTableModel) this.tblPlacas.getModel();
         modeloTabla.setRowCount(0);
         for (Placa placa : placas) {
             if (placa.isActiva()) {
                 activa="Si";
             }else{
                 activa="No";
             }
             Object[] fila = {
                placa.getNumeroPlaca(),
                 sdf.format(placa.getFechaExpedicion().getTime()),
                 sdf.format(placa.getFechaVigencia().getTime()),
                 placa.getTransporte().getNumSerie(),
                 "$"+placa.getCosto(),
                 activa
             };
             modeloTabla.addRow(fila);
         }
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPnlFondo() {
        return pnlFondo;
    }

    public void setPnlFondo(JPanel pnlFondo) {
        this.pnlFondo = pnlFondo;
    }

    public JPanel getPnlInfo() {
        return pnlInfo;
    }

    public void setPnlInfo(JPanel pnlInfo) {
        this.pnlInfo = pnlInfo;
    }

    public JPanel getPnlTablaLicencia() {
        return pnlTablaLicencia;
    }

    public void setPnlTablaLicencia(JPanel pnlTablaLicencia) {
        this.pnlTablaLicencia = pnlTablaLicencia;
    }

    public JPanel getPnlTablaPlacas() {
        return pnlTablaPlacas;
    }

    public void setPnlTablaPlacas(JPanel pnlTablaPlacas) {
        this.pnlTablaPlacas = pnlTablaPlacas;
    }

    public JPanel getPnlTitulo() {
        return pnlTitulo;
    }

    public void setPnlTitulo(JPanel pnlTitulo) {
        this.pnlTitulo = pnlTitulo;
    }

    public JScrollPane getScPanelLicencias() {
        return scPanelLicencias;
    }

    public void setScPanelLicencias(JScrollPane scPanelLicencias) {
        this.scPanelLicencias = scPanelLicencias;
    }

    public JTable getTblLicencias() {
        return tblLicencias;
    }

    public void setTblLicencias(JTable tblLicencias) {
        this.tblLicencias = tblLicencias;
    }

    public JTable getTblPlacas() {
        return tblPlacas;
    }

    public void setTblPlacas(JTable tblPlacas) {
        this.tblPlacas = tblPlacas;
    }

    public JLabel getTxtLicencias() {
        return txtLicencias;
    }

    public void setTxtLicencias(JLabel txtLicencias) {
        this.txtLicencias = txtLicencias;
    }

    public JLabel getTxtPlacas() {
        return txtPlacas;
    }

    public void setTxtPlacas(JLabel txtPlacas) {
        this.txtPlacas = txtPlacas;
    }

    public JLabel getTxtSolicitarPlacas() {
        return txtSolicitarPlacas;
    }

    public void setTxtSolicitarPlacas(JLabel txtSolicitarPlacas) {
        this.txtSolicitarPlacas = txtSolicitarPlacas;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.btnAtras);
        hash = 79 * hash + Objects.hashCode(this.jScrollPane1);
        hash = 79 * hash + Objects.hashCode(this.pnlFondo);
        hash = 79 * hash + Objects.hashCode(this.pnlInfo);
        hash = 79 * hash + Objects.hashCode(this.pnlTablaLicencia);
        hash = 79 * hash + Objects.hashCode(this.pnlTablaPlacas);
        hash = 79 * hash + Objects.hashCode(this.pnlTitulo);
        hash = 79 * hash + Objects.hashCode(this.scPanelLicencias);
        hash = 79 * hash + Objects.hashCode(this.tblLicencias);
        hash = 79 * hash + Objects.hashCode(this.tblPlacas);
        hash = 79 * hash + Objects.hashCode(this.txtLicencias);
        hash = 79 * hash + Objects.hashCode(this.txtPlacas);
        hash = 79 * hash + Objects.hashCode(this.txtSolicitarPlacas);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final frmConsultas other = (frmConsultas) obj;
        if (!Objects.equals(this.btnAtras, other.btnAtras)) {
            return false;
        }
        if (!Objects.equals(this.jScrollPane1, other.jScrollPane1)) {
            return false;
        }
        if (!Objects.equals(this.pnlFondo, other.pnlFondo)) {
            return false;
        }
        if (!Objects.equals(this.pnlInfo, other.pnlInfo)) {
            return false;
        }
        if (!Objects.equals(this.pnlTablaLicencia, other.pnlTablaLicencia)) {
            return false;
        }
        if (!Objects.equals(this.pnlTablaPlacas, other.pnlTablaPlacas)) {
            return false;
        }
        if (!Objects.equals(this.pnlTitulo, other.pnlTitulo)) {
            return false;
        }
        if (!Objects.equals(this.scPanelLicencias, other.scPanelLicencias)) {
            return false;
        }
        if (!Objects.equals(this.tblLicencias, other.tblLicencias)) {
            return false;
        }
        if (!Objects.equals(this.tblPlacas, other.tblPlacas)) {
            return false;
        }
        if (!Objects.equals(this.txtLicencias, other.txtLicencias)) {
            return false;
        }
        if (!Objects.equals(this.txtPlacas, other.txtPlacas)) {
            return false;
        }
        return Objects.equals(this.txtSolicitarPlacas, other.txtSolicitarPlacas);
    }

    @Override
    public String toString() {
        return "frmConsultas{" + "btnAtras=" + btnAtras + ", jScrollPane1=" + 
                jScrollPane1 + ", pnlFondo=" + pnlFondo + ", pnlInfo=" + pnlInfo + 
                ", pnlTablaLicencia=" + pnlTablaLicencia + ", pnlTablaPlacas=" + 
                pnlTablaPlacas + ", pnlTitulo=" + pnlTitulo + ", scPanelLicencias=" 
                + scPanelLicencias + ", tblLicencias=" + tblLicencias + ", tblPlacas="
                + tblPlacas + ", txtLicencias=" + txtLicencias + ", txtPlacas=" 
                + txtPlacas + ", txtSolicitarPlacas=" + txtSolicitarPlacas + '}';
    }

  
  
    

}
