/**
 *
 * Apr 7, 2023 9:28:56 PM
 *
 */
package Presentacion;

import Dominio.Licencia;
import Dominio.Persona;
import Dominio.Placa;
import Persistencia.LicenciasDAO;
import Persistencia.PersonasDAO;
import Persistencia.PlacasDAO;
import excepciones.PersistenciaException;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 * Descripción de la clase: Clase que permite poder seleccionar las personas de
 * las cuales se desea consultar las placas y licencias
 *
 * @author Joel Antonio Lopez Cota ID:228926 y David de Jesus Sotelo Palafox
 * ID:229384
 */
public class frmSolicitarReporte extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(frmSolicitarReporte.class.getName());
    private List<Persona> listaPersonas;
    private PersonasDAO personasDAO;
    private PlacasDAO placasDAO;
    private LicenciasDAO licenciasDAO;

    /**
     * Creates new form frmSeleccionPersonas
     */
    public frmSolicitarReporte() {
        initComponents();
        cargarOpcionesBusqueda();
        cargarTipoTramite();
        this.txtCampoNombre.setEnabled(false);
        this.dpFechaFin.setEnabled(false);
        this.dpFechaInicio.setEnabled(false);
        this.cbxTipoTramite.setEnabled(false);
        this.btnGenerarReporte.setEnabled(false);
        this.personasDAO = new PersonasDAO();
        this.licenciasDAO = new LicenciasDAO();
        this.placasDAO = new PlacasDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        txtSolicitarPlacas = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        pnlComponentes = new javax.swing.JPanel();
        cbxTipoConsulta = new javax.swing.JComboBox<>();
        pnlConsultas = new javax.swing.JPanel();
        dpFechaInicio = new com.github.lgooddatepicker.components.DatePicker();
        dpFechaFin = new com.github.lgooddatepicker.components.DatePicker();
        txtFechaFin = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JLabel();
        txtCampoNombre = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtTipoTramite = new javax.swing.JLabel();
        cbxTipoTramite = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de busqueda");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlTitulo.setBackground(new java.awt.Color(117, 37, 37));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(221, 66));

        txtSolicitarPlacas.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtSolicitarPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas.setText("Reportes");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlComponentes.setBackground(new java.awt.Color(255, 204, 153));

        cbxTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoConsulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoConsultaItemStateChanged(evt);
            }
        });
        cbxTipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoConsultaActionPerformed(evt);
            }
        });

        pnlConsultas.setBackground(new java.awt.Color(255, 204, 153));

        txtFechaFin.setBackground(new java.awt.Color(0, 0, 0));
        txtFechaFin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFechaFin.setText("Fecha Fin");

        txtFechaInicio.setBackground(new java.awt.Color(0, 0, 0));
        txtFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFechaInicio.setText("Fecha Inicio");

        txtCampoNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtCampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoNombreActionPerformed(evt);
            }
        });
        txtCampoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCampoNombreKeyTyped(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre.setText("Nombre");

        txtTipoTramite.setBackground(new java.awt.Color(0, 0, 0));
        txtTipoTramite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTipoTramite.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoTramite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipoTramite.setText("Tipo Tramite");

        cbxTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerarReporte.setText("Buscar");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtTipoTramite)
                    .addComponent(cbxTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCampoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFin)
                            .addComponent(dpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaFin)
                    .addComponent(txtFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTipoTramite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnGenerarReporte))
        );

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComponentesLayout = new javax.swing.GroupLayout(pnlComponentes);
        pnlComponentes.setLayout(pnlComponentesLayout);
        pnlComponentesLayout.setHorizontalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComponentesLayout.createSequentialGroup()
                        .addComponent(cbxTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlComponentesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlComponentesLayout.setVerticalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        try {
            this.dispose();
            new frmMenu().setVisible(true);

        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSolicitarReporte.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxTipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoConsultaActionPerformed

    }//GEN-LAST:event_cbxTipoConsultaActionPerformed

    private void cbxTipoConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoConsultaItemStateChanged
        try {
            switch (this.cbxTipoConsulta.getModel().getSelectedItem().toString()) {
                case "NOMBRE":
                    this.txtCampoNombre.setEnabled(true);
                    this.dpFechaFin.setEnabled(false);
                    this.dpFechaInicio.setEnabled(false);
                    this.cbxTipoTramite.setEnabled(false);
                    this.btnGenerarReporte.setEnabled(true);
                    break;
                case "PERIODO":
                    this.txtCampoNombre.setEnabled(false);
                    this.dpFechaFin.setEnabled(true);
                    this.dpFechaInicio.setEnabled(true);
                    this.cbxTipoTramite.setEnabled(false);
                    this.btnGenerarReporte.setEnabled(true);
                    break;
                case "TIPO TRAMITE":
                    this.txtCampoNombre.setEnabled(false);
                    this.dpFechaFin.setEnabled(false);
                    this.dpFechaInicio.setEnabled(false);
                    this.cbxTipoTramite.setEnabled(true);
                    this.btnGenerarReporte.setEnabled(true);
                    break;
            }
        } catch (NullPointerException nul) {
            nul.getMessage();

        }
    }//GEN-LAST:event_cbxTipoConsultaItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            new frmMenu().setVisible(true);
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSolicitarReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed

    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void txtCampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoNombreActionPerformed

    private void txtCampoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoNombreKeyTyped
    validacionCamposAlfabeto(evt);
    }//GEN-LAST:event_txtCampoNombreKeyTyped

    private void cargarOpcionesBusqueda() {
        this.cbxTipoConsulta.removeAllItems();
        this.cbxTipoConsulta.addItem("INDIQUE OPCION DE REPORTE");
        this.cbxTipoConsulta.addItem("NOMBRE");
        this.cbxTipoConsulta.addItem("PERIODO");
        this.cbxTipoConsulta.addItem("TIPO TRAMITE");
    }

    /**
     * 
     * Metodo para hacer las validaciones del campo alfabetico
     * @param evt 
     */
    private void validacionCamposAlfabeto(java.awt.event.KeyEvent evt) {
        char txt = evt.getKeyChar();
        if (!(Character.isAlphabetic(txt) || txt == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> cbxTipoConsulta;
    private javax.swing.JComboBox<String> cbxTipoTramite;
    private com.github.lgooddatepicker.components.DatePicker dpFechaFin;
    private com.github.lgooddatepicker.components.DatePicker dpFechaInicio;
    private javax.swing.JPanel pnlComponentes;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoNombre;
    private javax.swing.JLabel txtFechaFin;
    private javax.swing.JLabel txtFechaInicio;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtSolicitarPlacas;
    private javax.swing.JLabel txtTipoTramite;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * Metodo para cargar el tipo de tramite
     */
    private void cargarTipoTramite() {
       this.cbxTipoTramite.removeAllItems();
        this.cbxTipoTramite.addItem("INDIQUE El TIPO");
        this.cbxTipoTramite.addItem("LICENCIA");
        this.cbxTipoTramite.addItem("PLACAS");
    }

    public List<Persona> getListaPersonas() {
        return listaPersonas;
    }

    public void setListaPersonas(List<Persona> listaPersonas) {
        this.listaPersonas = listaPersonas;
    }

    public PersonasDAO getPersonasDAO() {
        return personasDAO;
    }

    public void setPersonasDAO(PersonasDAO personasDAO) {
        this.personasDAO = personasDAO;
    }

    public PlacasDAO getPlacasDAO() {
        return placasDAO;
    }

    public void setPlacasDAO(PlacasDAO placasDAO) {
        this.placasDAO = placasDAO;
    }

    public LicenciasDAO getLicenciasDAO() {
        return licenciasDAO;
    }

    public void setLicenciasDAO(LicenciasDAO licenciasDAO) {
        this.licenciasDAO = licenciasDAO;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnGenerarReporte() {
        return btnGenerarReporte;
    }

    public void setBtnGenerarReporte(JButton btnGenerarReporte) {
        this.btnGenerarReporte = btnGenerarReporte;
    }

    public JComboBox<String> getCbxTipoConsulta() {
        return cbxTipoConsulta;
    }

    public void setCbxTipoConsulta(JComboBox<String> cbxTipoConsulta) {
        this.cbxTipoConsulta = cbxTipoConsulta;
    }

    public JComboBox<String> getCbxTipoTramite() {
        return cbxTipoTramite;
    }

    public void setCbxTipoTramite(JComboBox<String> cbxTipoTramite) {
        this.cbxTipoTramite = cbxTipoTramite;
    }

    public DatePicker getDpFechaFin() {
        return dpFechaFin;
    }

    public void setDpFechaFin(DatePicker dpFechaFin) {
        this.dpFechaFin = dpFechaFin;
    }

    public DatePicker getDpFechaInicio() {
        return dpFechaInicio;
    }

    public void setDpFechaInicio(DatePicker dpFechaInicio) {
        this.dpFechaInicio = dpFechaInicio;
    }

    public JPanel getPnlComponentes() {
        return pnlComponentes;
    }

    public void setPnlComponentes(JPanel pnlComponentes) {
        this.pnlComponentes = pnlComponentes;
    }

    public JPanel getPnlConsultas() {
        return pnlConsultas;
    }

    public void setPnlConsultas(JPanel pnlConsultas) {
        this.pnlConsultas = pnlConsultas;
    }

    public JPanel getPnlFondo() {
        return pnlFondo;
    }

    public void setPnlFondo(JPanel pnlFondo) {
        this.pnlFondo = pnlFondo;
    }

    public JPanel getPnlTitulo() {
        return pnlTitulo;
    }

    public void setPnlTitulo(JPanel pnlTitulo) {
        this.pnlTitulo = pnlTitulo;
    }

    public JTextField getTxtCampoNombre() {
        return txtCampoNombre;
    }

    public void setTxtCampoNombre(JTextField txtCampoNombre) {
        this.txtCampoNombre = txtCampoNombre;
    }

    public JLabel getTxtFechaFin() {
        return txtFechaFin;
    }

    public void setTxtFechaFin(JLabel txtFechaFin) {
        this.txtFechaFin = txtFechaFin;
    }

    public JLabel getTxtFechaInicio() {
        return txtFechaInicio;
    }

    public void setTxtFechaInicio(JLabel txtFechaInicio) {
        this.txtFechaInicio = txtFechaInicio;
    }

    public JLabel getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JLabel txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JLabel getTxtSolicitarPlacas() {
        return txtSolicitarPlacas;
    }

    public void setTxtSolicitarPlacas(JLabel txtSolicitarPlacas) {
        this.txtSolicitarPlacas = txtSolicitarPlacas;
    }

    public JLabel getTxtTipoTramite() {
        return txtTipoTramite;
    }

    public void setTxtTipoTramite(JLabel txtTipoTramite) {
        this.txtTipoTramite = txtTipoTramite;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
    

}
