/**
 * frmSolicitarPlacasAutoUsado.java
 * Apr 6, 2023 12:53:31 PM
 *
 */
package Presentacion;

import Dominio.Automovil;
import Dominio.Persona;
import Dominio.Placa;
import Persistencia.AutomovilesDAO;
import Persistencia.LicenciasDAO;
import Persistencia.PersonasDAO;
import Persistencia.PlacasDAO;
import excepciones.PersistenciaException;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * Clase de tipo frame para solicitar las placas de un automovil usado
 * @author Joel Antonio Lopez Cota ID:228926 y David de Jesus Sotelo Palafox
 * ID:229384
 */
public class frmSolicitarPlacasAutoUsado extends javax.swing.JFrame {
//objetos - atributos
    private PersonasDAO personasDAO;
    private PlacasDAO placasDAO;
    private AutomovilesDAO automovilesDAO;
    private Persona personaProspecto;
    private Placa placaSolicitud;
    private LicenciasDAO licenciasDAO;
    private float costo=1000;
    /**
     * Creates new form frmSolicitarPlacasAutoUsado
     */
    public frmSolicitarPlacasAutoUsado() {
        initComponents();
        this.jPanel1.setVisible(true);
        this.pnlInfoPlacas.setVisible(false);
        this.pnlInfoPersona.setVisible(false);
        this.personasDAO = new PersonasDAO();
        this.placasDAO = new PlacasDAO();
        this.automovilesDAO = new AutomovilesDAO();
        this.licenciasDAO = new LicenciasDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        pnlPrincipal = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JPanel();
        txtRFC = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JLabel();
        txtCampoPlacas = new javax.swing.JTextField();
        txtCampoRFC = new javax.swing.JTextField();
        Separator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        txtCostoPlacas = new javax.swing.JLabel();
        btnBorrarCampos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlInfoPersona = new javax.swing.JPanel();
        txtRFCCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JLabel();
        txtFechaCliente = new javax.swing.JLabel();
        txtNumeroCliente = new javax.swing.JLabel();
        txtSolicitarPlacas2 = new javax.swing.JLabel();
        pnlInfoPlacas = new javax.swing.JPanel();
        txtPropietario = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        txtLinea = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtSolicitarPlacas1 = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        txtSolicitarPlacas = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setTitle("Solicitar Placas Auto Usado");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnlInformacion.setBackground(new java.awt.Color(255, 204, 153));

        txtRFC.setForeground(new java.awt.Color(0, 0, 0));
        txtRFC.setText("RFC");
        txtRFC.setAutoscrolls(true);

        txtPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacas.setText("Placas");

        txtCampoPlacas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCampoPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoPlacasActionPerformed(evt);
            }
        });

        txtCampoRFC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCampoRFC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCampoRFCMouseClicked(evt);
            }
        });
        txtCampoRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoRFCActionPerformed(evt);
            }
        });
        txtCampoRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCampoRFCKeyTyped(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        txtCostoPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtCostoPlacas.setText("Costo: 1000");

        btnBorrarCampos.setText("Borrar datos");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        pnlInfoPersona.setBackground(new java.awt.Color(255, 204, 153));

        txtRFCCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtRFCCliente.setMaximumSize(new java.awt.Dimension(0, 20));
        txtRFCCliente.setMinimumSize(new java.awt.Dimension(0, 20));
        txtRFCCliente.setPreferredSize(new java.awt.Dimension(10, 20));

        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setMaximumSize(new java.awt.Dimension(0, 20));
        txtNombreCliente.setMinimumSize(new java.awt.Dimension(0, 20));
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(10, 20));

        txtFechaCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaCliente.setMaximumSize(new java.awt.Dimension(0, 20));
        txtFechaCliente.setMinimumSize(new java.awt.Dimension(0, 20));
        txtFechaCliente.setPreferredSize(new java.awt.Dimension(10, 20));

        txtNumeroCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroCliente.setMaximumSize(new java.awt.Dimension(0, 20));
        txtNumeroCliente.setMinimumSize(new java.awt.Dimension(0, 20));
        txtNumeroCliente.setPreferredSize(new java.awt.Dimension(10, 20));

        txtSolicitarPlacas2.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtSolicitarPlacas2.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas2.setText("Informacion Cliente");

        javax.swing.GroupLayout pnlInfoPersonaLayout = new javax.swing.GroupLayout(pnlInfoPersona);
        pnlInfoPersona.setLayout(pnlInfoPersonaLayout);
        pnlInfoPersonaLayout.setHorizontalGroup(
            pnlInfoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoPersonaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlInfoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSolicitarPlacas2)
                    .addGroup(pnlInfoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFechaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRFCCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        pnlInfoPersonaLayout.setVerticalGroup(
            pnlInfoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoPersonaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtSolicitarPlacas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRFCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInfoPlacas.setBackground(new java.awt.Color(255, 204, 153));

        txtPropietario.setForeground(new java.awt.Color(0, 0, 0));
        txtPropietario.setMaximumSize(new java.awt.Dimension(0, 20));
        txtPropietario.setMinimumSize(new java.awt.Dimension(0, 20));
        txtPropietario.setPreferredSize(new java.awt.Dimension(10, 20));

        txtModelo.setForeground(new java.awt.Color(0, 0, 0));
        txtModelo.setMaximumSize(new java.awt.Dimension(0, 20));
        txtModelo.setMinimumSize(new java.awt.Dimension(0, 20));
        txtModelo.setPreferredSize(new java.awt.Dimension(10, 20));

        txtLinea.setForeground(new java.awt.Color(0, 0, 0));
        txtLinea.setMaximumSize(new java.awt.Dimension(0, 20));
        txtLinea.setMinimumSize(new java.awt.Dimension(0, 20));
        txtLinea.setPreferredSize(new java.awt.Dimension(10, 20));

        txtColor.setForeground(new java.awt.Color(0, 0, 0));
        txtColor.setMaximumSize(new java.awt.Dimension(0, 20));
        txtColor.setMinimumSize(new java.awt.Dimension(0, 20));
        txtColor.setPreferredSize(new java.awt.Dimension(10, 20));

        txtMarca.setForeground(new java.awt.Color(0, 0, 0));
        txtMarca.setMaximumSize(new java.awt.Dimension(0, 20));
        txtMarca.setMinimumSize(new java.awt.Dimension(0, 20));
        txtMarca.setPreferredSize(new java.awt.Dimension(10, 20));

        txtSolicitarPlacas1.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtSolicitarPlacas1.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas1.setText("Informacion Placa");

        javax.swing.GroupLayout pnlInfoPlacasLayout = new javax.swing.GroupLayout(pnlInfoPlacas);
        pnlInfoPlacas.setLayout(pnlInfoPlacasLayout);
        pnlInfoPlacasLayout.setHorizontalGroup(
            pnlInfoPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoPlacasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlInfoPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSolicitarPlacas1)
                    .addGroup(pnlInfoPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoPlacasLayout.setVerticalGroup(
            pnlInfoPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoPlacasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlInfoPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInfoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRFC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlacas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformacionLayout.createSequentialGroup()
                                .addComponent(txtCampoPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInformacionLayout.createSequentialGroup()
                                .addComponent(txtCampoRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCostoPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Separator1)
                .addContainerGap())
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRFC)
                            .addComponent(txtCampoRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(49, 49, 49)
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacas)
                            .addComponent(txtCampoPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCostoPlacas)
                        .addGap(18, 18, 18)))
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pnlTitulo.setBackground(new java.awt.Color(117, 37, 37));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(221, 66));

        txtSolicitarPlacas.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtSolicitarPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas.setText("Solicitar Placas");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoPlacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoPlacasActionPerformed

    private void txtCampoRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoRFCActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            new frmMenu().setVisible(true);
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSolicitarPlacasAutoUsado.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCampoRFCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCampoRFCMouseClicked

    }//GEN-LAST:event_txtCampoRFCMouseClicked

    private void txtCampoRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoRFCKeyTyped
        if (!(txtCampoRFC.getText().length() > 12)) {
            validacionNumeroLetra(evt);
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtCampoRFCKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.txtCampoRFC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un RFC valido");
        } else {
            try {
                if (licenciasDAO.buscarLicenciaRFC(personasDAO.buscarPersonaRFC(txtCampoRFC.getText())) != null) {
                    personaProspecto = personasDAO.buscarPersonaRFC(this.txtCampoRFC.getText());
                    setearInfoPersona(personaProspecto);
                } else {
                    JOptionPane.showMessageDialog(this, "El cliente no cuenta con una licencia valida");
                }
            } catch (PersistenciaException ex) {
                Logger.getLogger(frmSolicitarPlacasAutoNuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.txtCampoPlacas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una serie valido");
        } else {
            if (placasDAO.buscarPersonaSerie(txtCampoPlacas.getText()) != null) {
                placaSolicitud = placasDAO.buscarPersonaSerie(txtCampoPlacas.getText());
                setearInfoPlaca(placaSolicitud);
            } else {
                JOptionPane.showMessageDialog(this, "El RFC no existe");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        generarCambiosPlacas();
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            new frmMenu().setVisible(true);
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSolicitarPlacasAutoUsado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    
    /**
     * 
     * Metodo que ayuda a setear la informacion de la persona.
     * @param persona objeto persona.
     */
    private void setearInfoPersona(Persona persona) {
        this.pnlInfoPersona.setVisible(true);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.txtRFCCliente.setText("RFC: " + persona.getRFC());
        this.txtNombreCliente.setText("Nombre: " + persona.getNombreCompleto());
        this.txtFechaCliente.setText("Fecha Nacimiento: " + sdf.format(persona.getFechaNacimiento().getTime()));
        this.txtNumeroCliente.setText("Numero Telefono: " + persona.getTelefono());
    }

    /**
     * 
     * Metodo para setear la informacion de la placa.
     * @param placa objeto tipo placa.
     */
    private void setearInfoPlaca(Placa placa) {
        this.pnlInfoPlacas.setVisible(true);
        this.txtPropietario.setText("Propietario: " + placa.getPersona().getNombreCompleto());
        this.txtModelo.setText("Modelo: " + placa.getTransporte().getModelo());
        this.txtLinea.setText("Linea: " + placa.getTransporte().getLinea());
        this.txtColor.setText("Color: " + placa.getTransporte().getColor());
        this.txtMarca.setText("Marca: " + placa.getTransporte().getMarca());

    }

    /**
     * 
     * Metodo para generar el numero de serie.
     * @return el String del numero de serie.
     */
    public String generarNumeroSerie() {
        StringBuilder numeroSerie = new StringBuilder();
        Random random = new Random();
        String letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        for (int i = 0; i < 3; i++) {
            char letra = letras.charAt(random.nextInt(letras.length()));
            numeroSerie.append(letra);
        }
        numeroSerie.append("-");
        for (int i = 0; i < 3; i++) {
            int numero = random.nextInt(10);
            numeroSerie.append(numero);
        }
        return numeroSerie.toString();
    }

    public PersonasDAO getPersonasDAO() {
        return personasDAO;
    }

    public void setPersonasDAO(PersonasDAO personasDAO) {
        this.personasDAO = personasDAO;
    }

    public PlacasDAO getPlacasDAO() {
        return placasDAO;
    }

    public void setPlacasDAO(PlacasDAO placasDAO) {
        this.placasDAO = placasDAO;
    }

    public AutomovilesDAO getAutomovilesDAO() {
        return automovilesDAO;
    }

    public void setAutomovilesDAO(AutomovilesDAO automovilesDAO) {
        this.automovilesDAO = automovilesDAO;
    }

    public Persona getPersonaProspecto() {
        return personaProspecto;
    }

    public void setPersonaProspecto(Persona personaProspecto) {
        this.personaProspecto = personaProspecto;
    }

    public Placa getPlacaSolicitud() {
        return placaSolicitud;
    }

    public void setPlacaSolicitud(Placa placaSolicitud) {
        this.placaSolicitud = placaSolicitud;
    }

    public LicenciasDAO getLicenciasDAO() {
        return licenciasDAO;
    }

    public void setLicenciasDAO(LicenciasDAO licenciasDAO) {
        this.licenciasDAO = licenciasDAO;
    }

    public float getCosto() {
        return costo;
    }

    public void setCosto(float costo) {
        this.costo = costo;
    }

    public JSeparator getSeparator1() {
        return Separator1;
    }

    public void setSeparator1(JSeparator Separator1) {
        this.Separator1 = Separator1;
    }

    public JButton getBtnBorrarCampos() {
        return btnBorrarCampos;
    }

    public void setBtnBorrarCampos(JButton btnBorrarCampos) {
        this.btnBorrarCampos = btnBorrarCampos;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnSolicitar() {
        return btnSolicitar;
    }

    public void setBtnSolicitar(JButton btnSolicitar) {
        this.btnSolicitar = btnSolicitar;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    public void setjCheckBoxMenuItem1(JCheckBoxMenuItem jCheckBoxMenuItem1) {
        this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getPnlInfoPersona() {
        return pnlInfoPersona;
    }

    public void setPnlInfoPersona(JPanel pnlInfoPersona) {
        this.pnlInfoPersona = pnlInfoPersona;
    }

    public JPanel getPnlInfoPlacas() {
        return pnlInfoPlacas;
    }

    public void setPnlInfoPlacas(JPanel pnlInfoPlacas) {
        this.pnlInfoPlacas = pnlInfoPlacas;
    }

    public JPanel getPnlInformacion() {
        return pnlInformacion;
    }

    public void setPnlInformacion(JPanel pnlInformacion) {
        this.pnlInformacion = pnlInformacion;
    }

    public JPanel getPnlPrincipal() {
        return pnlPrincipal;
    }

    public void setPnlPrincipal(JPanel pnlPrincipal) {
        this.pnlPrincipal = pnlPrincipal;
    }

    public JPanel getPnlTitulo() {
        return pnlTitulo;
    }

    public void setPnlTitulo(JPanel pnlTitulo) {
        this.pnlTitulo = pnlTitulo;
    }

    public JTextField getTxtCampoPlacas() {
        return txtCampoPlacas;
    }

    public void setTxtCampoPlacas(JTextField txtCampoPlacas) {
        this.txtCampoPlacas = txtCampoPlacas;
    }

    public JTextField getTxtCampoRFC() {
        return txtCampoRFC;
    }

    public void setTxtCampoRFC(JTextField txtCampoRFC) {
        this.txtCampoRFC = txtCampoRFC;
    }

    public JLabel getTxtColor() {
        return txtColor;
    }

    public void setTxtColor(JLabel txtColor) {
        this.txtColor = txtColor;
    }

    public JLabel getTxtCostoPlacas() {
        return txtCostoPlacas;
    }

    public void setTxtCostoPlacas(JLabel txtCostoPlacas) {
        this.txtCostoPlacas = txtCostoPlacas;
    }

    public JLabel getTxtFechaCliente() {
        return txtFechaCliente;
    }

    public void setTxtFechaCliente(JLabel txtFechaCliente) {
        this.txtFechaCliente = txtFechaCliente;
    }

    public JLabel getTxtLinea() {
        return txtLinea;
    }

    public void setTxtLinea(JLabel txtLinea) {
        this.txtLinea = txtLinea;
    }

    public JLabel getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JLabel txtMarca) {
        this.txtMarca = txtMarca;
    }

    public JLabel getTxtModelo() {
        return txtModelo;
    }

    public void setTxtModelo(JLabel txtModelo) {
        this.txtModelo = txtModelo;
    }

    public JLabel getTxtNombreCliente() {
        return txtNombreCliente;
    }

    public void setTxtNombreCliente(JLabel txtNombreCliente) {
        this.txtNombreCliente = txtNombreCliente;
    }

    public JLabel getTxtNumeroCliente() {
        return txtNumeroCliente;
    }

    public void setTxtNumeroCliente(JLabel txtNumeroCliente) {
        this.txtNumeroCliente = txtNumeroCliente;
    }

    public JLabel getTxtPlacas() {
        return txtPlacas;
    }

    public void setTxtPlacas(JLabel txtPlacas) {
        this.txtPlacas = txtPlacas;
    }

    public JLabel getTxtPropietario() {
        return txtPropietario;
    }

    public void setTxtPropietario(JLabel txtPropietario) {
        this.txtPropietario = txtPropietario;
    }

    public JLabel getTxtRFC() {
        return txtRFC;
    }

    public void setTxtRFC(JLabel txtRFC) {
        this.txtRFC = txtRFC;
    }

    public JLabel getTxtRFCCliente() {
        return txtRFCCliente;
    }

    public void setTxtRFCCliente(JLabel txtRFCCliente) {
        this.txtRFCCliente = txtRFCCliente;
    }

    public JLabel getTxtSolicitarPlacas() {
        return txtSolicitarPlacas;
    }

    public void setTxtSolicitarPlacas(JLabel txtSolicitarPlacas) {
        this.txtSolicitarPlacas = txtSolicitarPlacas;
    }

    public JLabel getTxtSolicitarPlacas1() {
        return txtSolicitarPlacas1;
    }

    public void setTxtSolicitarPlacas1(JLabel txtSolicitarPlacas1) {
        this.txtSolicitarPlacas1 = txtSolicitarPlacas1;
    }

    public JLabel getTxtSolicitarPlacas2() {
        return txtSolicitarPlacas2;
    }

    public void setTxtSolicitarPlacas2(JLabel txtSolicitarPlacas2) {
        this.txtSolicitarPlacas2 = txtSolicitarPlacas2;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator1;
    private javax.swing.JButton btnBorrarCampos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlInfoPersona;
    private javax.swing.JPanel pnlInfoPlacas;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoPlacas;
    private javax.swing.JTextField txtCampoRFC;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtCostoPlacas;
    private javax.swing.JLabel txtFechaCliente;
    private javax.swing.JLabel txtLinea;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtNombreCliente;
    private javax.swing.JLabel txtNumeroCliente;
    private javax.swing.JLabel txtPlacas;
    private javax.swing.JLabel txtPropietario;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JLabel txtRFCCliente;
    private javax.swing.JLabel txtSolicitarPlacas;
    private javax.swing.JLabel txtSolicitarPlacas1;
    private javax.swing.JLabel txtSolicitarPlacas2;
    // End of variables declaration//GEN-END:variables

    private void validacionNumeroLetra(KeyEvent evt) {
        char txt = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(txt))) {
            evt.consume();
        }
    }

    private void generarCambiosPlacas() {

        try {
            placaSolicitud.setNumeroPlaca(generarNumeroSerie());
            placaSolicitud.setCosto(costo);
            placasDAO.actualizar(placaSolicitud);
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSolicitarPlacasAutoUsado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
