/**
 *
 * Apr 7, 2023 9:28:56 PM
 *
 */
package Presentacion;

import Dominio.Licencia;
import Dominio.Persona;
import Dominio.Placa;
import Persistencia.LicenciasDAO;
import Persistencia.PersonasDAO;
import Persistencia.PlacasDAO;
import excepciones.PersistenciaException;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 * Descripción de la clase: Clase que permite poder seleccionar las personas de
 * las cuales se desea consultar las placas y licencias
 *
 * @author Joel Antonio Lopez Cota ID:228926 y David de Jesus Sotelo Palafox
 * ID:229384
 */
public class frmSeleccionPersonas extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(frmSeleccionPersonas.class.getName());
    private Integer elementoSeleccionado;
    private List<Persona> listaPersonas;
    private PersonasDAO personasDAO;
    private PlacasDAO placasDAO;
    private LicenciasDAO licenciasDAO;
    int largo = 15;
    int opcion = 1;

    /**
     * Creates new form frmSeleccionPersonas
     */
    public frmSeleccionPersonas() {
        initComponents();
        cargarOpcionesBusqueda();
        this.txtCampo.setEnabled(false);
        this.pnlTablas.setVisible(false);
        this.personasDAO = new PersonasDAO();
        this.licenciasDAO = new LicenciasDAO();
        this.placasDAO = new PlacasDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        txtSolicitarPlacas = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        pnlComponentes = new javax.swing.JPanel();
        cbxTipoConsulta = new javax.swing.JComboBox<>();
        txtCampo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlTablas = new javax.swing.JPanel();
        jScrollResultados = new javax.swing.JScrollPane();
        listaResultados = new javax.swing.JList<>();
        txtSeleccionados = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de busqueda");
        setResizable(false);

        pnlTitulo.setBackground(new java.awt.Color(117, 37, 37));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(221, 66));

        txtSolicitarPlacas.setBackground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtSolicitarPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtSolicitarPlacas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSolicitarPlacas.setText("Consultas");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlComponentes.setBackground(new java.awt.Color(255, 204, 153));

        cbxTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoConsulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoConsultaItemStateChanged(evt);
            }
        });
        cbxTipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoConsultaActionPerformed(evt);
            }
        });

        txtCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCampoKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        pnlTablas.setBackground(new java.awt.Color(255, 204, 153));

        listaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaResultadosMouseClicked(evt);
            }
        });
        jScrollResultados.setViewportView(listaResultados);

        txtSeleccionados.setForeground(new java.awt.Color(0, 0, 0));
        txtSeleccionados.setText("Resultados");

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablasLayout = new javax.swing.GroupLayout(pnlTablas);
        pnlTablas.setLayout(pnlTablasLayout);
        pnlTablasLayout.setHorizontalGroup(
            pnlTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablasLayout.createSequentialGroup()
                        .addComponent(txtSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablasLayout.createSequentialGroup()
                        .addGroup(pnlTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTablasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnContinuar))
                            .addComponent(jScrollResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        pnlTablasLayout.setVerticalGroup(
            pnlTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSeleccionados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComponentesLayout = new javax.swing.GroupLayout(pnlComponentes);
        pnlComponentes.setLayout(pnlComponentesLayout);
        pnlComponentesLayout.setHorizontalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComponentesLayout.createSequentialGroup()
                        .addComponent(cbxTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlComponentesLayout.setVerticalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtras)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.generarPersonas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        try {
            this.dispose();
            new frmMenu().setVisible(true);

        } catch (PersistenciaException ex) {
            Logger.getLogger(frmSeleccionPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxTipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoConsultaActionPerformed
        if (this.cbxTipoConsulta.getSelectedItem() == "INDIQUE OPCION DE CONSULTA") {
            this.txtCampo.setEnabled(false);
        } else {
            this.txtCampo.setEnabled(true);
        }
    }//GEN-LAST:event_cbxTipoConsultaActionPerformed

    private void cbxTipoConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoConsultaItemStateChanged
        try {
            switch (this.cbxTipoConsulta.getModel().getSelectedItem().toString()) {
                case "RFC":
                    largo = 15;
                    opcion = 1;
                    break;
                case "NOMBRE":
                    largo = 20;
                    opcion = 2;
                    break;
                case "AÑO NACIDO":
                    largo = 3;
                    opcion = 3;
                    break;
            }
        } catch (NullPointerException nul) {
            nul.getMessage();

        }
    }//GEN-LAST:event_cbxTipoConsultaItemStateChanged

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (elementoSeleccionado != null) {
            Persona persona = listaPersonas.get(elementoSeleccionado);
            List<Licencia> listaLicencias = licenciasDAO.listaLicencias(persona);
            List<Placa> listaPlacas = placasDAO.listaPlacas(persona);
            if (listaPlacas.isEmpty() && listaLicencias.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El cliente no cuenta con un historial");
            } else {
                new frmConsultas(listaLicencias, listaPlacas).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un elemento");
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * Lista de resulados
     * @param evt  eventos
     */
    private void listaResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaResultadosMouseClicked
        elementoSeleccionado = this.listaResultados.getSelectedIndex();
    }//GEN-LAST:event_listaResultadosMouseClicked

    /**
     * Metodo de casos
     * @param evt eventos
     */
    private void txtCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoKeyTyped
        if (!(txtCampo.getText().length() > largo)) {
            switch (opcion) {
                case 1:
                validacionRFC(evt);
                break;
                case 2:
                validacionCamposAlfabeto(evt);
                break;
                default:
                validacionNumero(evt);
                break;
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtCampoKeyTyped

    /**
     * 
     * Metodo para cargar la tabla de los resutados
     * @param personas Lista de personas
     */
    private void cargarTablaResultados(List<Persona> personas) {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Persona persona : personas) {
            listModel.addElement(persona.toString());
        }
        this.listaResultados.setModel(listModel);
        this.listaResultados.revalidate();
        this.listaResultados.repaint();
    }

    /**
     * 
     * Metodo para cargar las opciones de busqueda
     */
    private void cargarOpcionesBusqueda() {
        this.cbxTipoConsulta.removeAllItems();
        this.cbxTipoConsulta.addItem("INDIQUE OPCION DE REPORTE");
        this.cbxTipoConsulta.addItem("PERIODO");
        this.cbxTipoConsulta.addItem("NOMBRE");
        this.cbxTipoConsulta.addItem("TIPO TRAMITE");

    }

    /**
     * Metodo para validar el numero
     * @param evt evento
     */
    private void validacionNumero(java.awt.event.KeyEvent evt) {
        char txt = evt.getKeyChar();
        if (!(Character.isDigit(txt))) {
            evt.consume();
        }
    }

    /**
     * 
     * Metodo para validar el campo alfabetico
     * @param evt evento
     */
    private void validacionCamposAlfabeto(java.awt.event.KeyEvent evt) {
        char txt = evt.getKeyChar();
        if (!(Character.isAlphabetic(txt) || txt == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }

    /**
     * 
     * Metodo para validar el RFC de la persona
     * @param evt evento
     */
    private void validacionRFC(java.awt.event.KeyEvent evt) {
        char txt = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(txt))) {
            evt.consume();
        }
    }

    /**
     * 
     * Metodo para generar las personas.
     */
    private void generarPersonas() {
        String opcion = this.cbxTipoConsulta.getModel().getSelectedItem().toString();
        if (this.txtCampo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un dato valido");

        } else {
            switch (opcion) {
                case "RFC": {
                    try {
                        Persona persona = personasDAO.buscarPersonaRFC(this.txtCampo.getText());
                        if (persona != null) {
                            listaPersonas = new ArrayList<>();
                            listaPersonas.add(persona);
                            cargarTablaResultados(listaPersonas);
                            this.pnlTablas.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(this, "No se encontraron resultados\nVerifique los datos");
                        }
                    } catch (PersistenciaException ex) {
                        Logger.getLogger(frmSeleccionPersonas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
                case "NOMBRE":
                    listaPersonas = personasDAO.buscarPersonasPorNombre(this.txtCampo.getText());
                    if (listaPersonas != null) {
                        cargarTablaResultados(listaPersonas);
                        this.pnlTablas.setVisible(true);
                    } else {
                        this.pnlTablas.setVisible(false);
                        JOptionPane.showMessageDialog(this, "No se encontraron resultados");
                    }
                    break;
                case "AÑO NACIDO":
                    listaPersonas = personasDAO.buscarFecha(parseInt(this.txtCampo.getText()));
                    if (listaPersonas != null) {
                        cargarTablaResultados(listaPersonas);
                        this.pnlTablas.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontraron resultados");
                    }
                    break;
                default:
            }
        }
    }

    public Integer getElementoSeleccionado() {
        return elementoSeleccionado;
    }

    public void setElementoSeleccionado(Integer elementoSeleccionado) {
        this.elementoSeleccionado = elementoSeleccionado;
    }

    public List<Persona> getListaPersonas() {
        return listaPersonas;
    }

    public void setListaPersonas(List<Persona> listaPersonas) {
        this.listaPersonas = listaPersonas;
    }

    public PersonasDAO getPersonasDAO() {
        return personasDAO;
    }

    public void setPersonasDAO(PersonasDAO personasDAO) {
        this.personasDAO = personasDAO;
    }

    public PlacasDAO getPlacasDAO() {
        return placasDAO;
    }

    public void setPlacasDAO(PlacasDAO placasDAO) {
        this.placasDAO = placasDAO;
    }

    public LicenciasDAO getLicenciasDAO() {
        return licenciasDAO;
    }

    public void setLicenciasDAO(LicenciasDAO licenciasDAO) {
        this.licenciasDAO = licenciasDAO;
    }

    public int getLargo() {
        return largo;
    }

    public void setLargo(int largo) {
        this.largo = largo;
    }

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnContinuar() {
        return btnContinuar;
    }

    public void setBtnContinuar(JButton btnContinuar) {
        this.btnContinuar = btnContinuar;
    }

    public JComboBox<String> getCbxTipoConsulta() {
        return cbxTipoConsulta;
    }

    public void setCbxTipoConsulta(JComboBox<String> cbxTipoConsulta) {
        this.cbxTipoConsulta = cbxTipoConsulta;
    }

    public JScrollPane getjScrollResultados() {
        return jScrollResultados;
    }

    public void setjScrollResultados(JScrollPane jScrollResultados) {
        this.jScrollResultados = jScrollResultados;
    }

    public JList<String> getListaResultados() {
        return listaResultados;
    }

    public void setListaResultados(JList<String> listaResultados) {
        this.listaResultados = listaResultados;
    }

    public JPanel getPnlComponentes() {
        return pnlComponentes;
    }

    public void setPnlComponentes(JPanel pnlComponentes) {
        this.pnlComponentes = pnlComponentes;
    }

    public JPanel getPnlFondo() {
        return pnlFondo;
    }

    public void setPnlFondo(JPanel pnlFondo) {
        this.pnlFondo = pnlFondo;
    }

    public JPanel getPnlTablas() {
        return pnlTablas;
    }

    public void setPnlTablas(JPanel pnlTablas) {
        this.pnlTablas = pnlTablas;
    }

    public JPanel getPnlTitulo() {
        return pnlTitulo;
    }

    public void setPnlTitulo(JPanel pnlTitulo) {
        this.pnlTitulo = pnlTitulo;
    }

    public JTextField getTxtCampo() {
        return txtCampo;
    }

    public void setTxtCampo(JTextField txtCampo) {
        this.txtCampo = txtCampo;
    }

    public JLabel getTxtSeleccionados() {
        return txtSeleccionados;
    }

    public void setTxtSeleccionados(JLabel txtSeleccionados) {
        this.txtSeleccionados = txtSeleccionados;
    }

    public JLabel getTxtSolicitarPlacas() {
        return txtSolicitarPlacas;
    }

    public void setTxtSolicitarPlacas(JLabel txtSolicitarPlacas) {
        this.txtSolicitarPlacas = txtSolicitarPlacas;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.elementoSeleccionado);
        hash = 89 * hash + Objects.hashCode(this.listaPersonas);
        hash = 89 * hash + Objects.hashCode(this.personasDAO);
        hash = 89 * hash + Objects.hashCode(this.placasDAO);
        hash = 89 * hash + Objects.hashCode(this.licenciasDAO);
        hash = 89 * hash + this.largo;
        hash = 89 * hash + this.opcion;
        hash = 89 * hash + Objects.hashCode(this.btnAtras);
        hash = 89 * hash + Objects.hashCode(this.btnBuscar);
        hash = 89 * hash + Objects.hashCode(this.btnContinuar);
        hash = 89 * hash + Objects.hashCode(this.cbxTipoConsulta);
        hash = 89 * hash + Objects.hashCode(this.jScrollResultados);
        hash = 89 * hash + Objects.hashCode(this.listaResultados);
        hash = 89 * hash + Objects.hashCode(this.pnlComponentes);
        hash = 89 * hash + Objects.hashCode(this.pnlFondo);
        hash = 89 * hash + Objects.hashCode(this.pnlTablas);
        hash = 89 * hash + Objects.hashCode(this.pnlTitulo);
        hash = 89 * hash + Objects.hashCode(this.txtCampo);
        hash = 89 * hash + Objects.hashCode(this.txtSeleccionados);
        hash = 89 * hash + Objects.hashCode(this.txtSolicitarPlacas);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final frmSeleccionPersonas other = (frmSeleccionPersonas) obj;
        if (this.largo != other.largo) {
            return false;
        }
        if (this.opcion != other.opcion) {
            return false;
        }
        if (!Objects.equals(this.elementoSeleccionado, other.elementoSeleccionado)) {
            return false;
        }
        if (!Objects.equals(this.listaPersonas, other.listaPersonas)) {
            return false;
        }
        if (!Objects.equals(this.personasDAO, other.personasDAO)) {
            return false;
        }
        if (!Objects.equals(this.placasDAO, other.placasDAO)) {
            return false;
        }
        if (!Objects.equals(this.licenciasDAO, other.licenciasDAO)) {
            return false;
        }
        if (!Objects.equals(this.btnAtras, other.btnAtras)) {
            return false;
        }
        if (!Objects.equals(this.btnBuscar, other.btnBuscar)) {
            return false;
        }
        if (!Objects.equals(this.btnContinuar, other.btnContinuar)) {
            return false;
        }
        if (!Objects.equals(this.cbxTipoConsulta, other.cbxTipoConsulta)) {
            return false;
        }
        if (!Objects.equals(this.jScrollResultados, other.jScrollResultados)) {
            return false;
        }
        if (!Objects.equals(this.listaResultados, other.listaResultados)) {
            return false;
        }
        if (!Objects.equals(this.pnlComponentes, other.pnlComponentes)) {
            return false;
        }
        if (!Objects.equals(this.pnlFondo, other.pnlFondo)) {
            return false;
        }
        if (!Objects.equals(this.pnlTablas, other.pnlTablas)) {
            return false;
        }
        if (!Objects.equals(this.pnlTitulo, other.pnlTitulo)) {
            return false;
        }
        if (!Objects.equals(this.txtCampo, other.txtCampo)) {
            return false;
        }
        if (!Objects.equals(this.txtSeleccionados, other.txtSeleccionados)) {
            return false;
        }
        return Objects.equals(this.txtSolicitarPlacas, other.txtSolicitarPlacas);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbxTipoConsulta;
    private javax.swing.JScrollPane jScrollResultados;
    private javax.swing.JList<String> listaResultados;
    private javax.swing.JPanel pnlComponentes;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTablas;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampo;
    private javax.swing.JLabel txtSeleccionados;
    private javax.swing.JLabel txtSolicitarPlacas;
    // End of variables declaration//GEN-END:variables

}
